name: Build vsce package

on:
  workflow_dispatch:

  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env RELEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set env VERSION
        run: echo "VERSION=$(grep version package.json | sed -r 's/",/"/' |  sed 's/"//g' | sed 's/[[:space:]]*version:[[:space:]]*//1')" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install vsce
        run: npm install --global @vscode/vsce

      - name: Build
        run: vsce package --no-yarn
        # run: yarn vsce-packge

      # - name: Create pkg dist dir
      #   run: mkdir pkg-dist

      # - name: Move
      #   run: mv keil-vscode-assistant-${{ env.VERSION }}.vsix pkg-dist/

      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: build-result
      #     path: |
      #       pkg-dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: false
          append_body: true
          files: |
            keil-vscode-assistant-${{ env.VERSION }}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
