name: Build vsce package

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install Yarn
        run: npm install -g yarn

      - name: Install VSCE
        run: npm install -g vsce

      - name: Install dependencies
        run: yarn install

      - name: Build package
        run: vsce package --yarn

      - name: Set env RELEASE_VERSION
        if: success()
        run: 
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Extract Release Notes from CHANGELOG.md
        if: success()
        run: |
          VERSION=${{ env.VERSION }}
          awk "/^## \[v${VERSION}\]/ {flag=1; next} /^## \[/ {flag=0} flag" CHANGELOG.md > RELEASE_BODY.md

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: success() && github.ref_type == 'tag'
        with:
          body_path: RELEASE_BODY.md
          draft: false
          prerelease: false
          files: keil-vscode-assistant-${{ env.VERSION }}.vsix
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Publish to Marketplace
        if: success() && github.ref_type == 'tag'
        run: npx vsce publish -p ${{ secrets.VSCE_PAT }}
